### ISSUE TITLE
not working inside JBoss7 container?

### ISSUE THREAD

**Issue by think-01** [inner-loop/java-neo4j-ogm#3]
22:11:25,562 WARN  [org.jboss.as.server.deployment](MSC service thread 1-4) JBAS015852: Could not index class io/innerloop/neo4j/client/spi/impl/rest/RestConnectionImpl.class at /C:/JBoss/jboss-eap-6.3/bin/content/CityMiners.war/WEB-INF/lib/java-neo4j-client-0.2.0.jar: java.lang.IllegalStateException: Unknown tag! pos=72 poolCount = 396
    at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:606) [jandex-1.0.3.Final-redhat-2.jar:1.0.3.Final-redhat-2]
    at org.jboss.jandex.Indexer.index(Indexer.java:640) [jandex-1.0.3.Final-redhat-2.jar:1.0.3.Final-redhat-2]
    at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:100) [jboss-as-server-7.4.0.Final-redhat-19.jar:7.4.0.Final-redhat-19]
    at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51) [jboss-as-server-7.4.0.Final-redhat-19.jar:7.4.0.Final-redhat-19]
    at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:159) [jboss-as-server-7.4.0.Final-redhat-19.jar:7.4.0.Final-redhat-19]
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1980) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1913) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_60-ea]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_60-ea]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_60-ea]

22:11:25,578 WARN  [org.jboss.as.server.deployment](MSC service thread 1-4) JBAS015852: Could not index class io/innerloop/neo4j/ogm/Session.class at /C:/JBoss/jboss-eap-6.3/bin/content/CityMiners.war/WEB-INF/lib/java-neo4j-ogm-0.1.0.jar: java.lang.IllegalStateException: Unknown tag! pos=37 poolCount = 569
    at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:606) [jandex-1.0.3.Final-redhat-2.jar:1.0.3.Final-redhat-2]
    at org.jboss.jandex.Indexer.index(Indexer.java:640) [jandex-1.0.3.Final-redhat-2.jar:1.0.3.Final-redhat-2]
    at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:100) [jboss-as-server-7.4.0.Final-redhat-19.jar:7.4.0.Final-redhat-19]
    at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51) [jboss-as-server-7.4.0.Final-redhat-19.jar:7.4.0.Final-redhat-19]
    at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:159) [jboss-as-server-7.4.0.Final-redhat-19.jar:7.4.0.Final-redhat-19]
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1980) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1913) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_60-ea]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_60-ea]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_60-ea]

22:11:25,578 WARN  [org.jboss.as.server.deployment](MSC service thread 1-4) JBAS015852: Could not index class io/innerloop/neo4j/ogm/impl/mapping/CypherQueryMapper.class at /C:/JBoss/jboss-eap-6.3/bin/content/CityMiners.war/WEB-INF/lib/java-neo4j-ogm-0.1.0.jar: java.lang.IllegalStateException: Unknown tag! pos=51 poolCount = 592
    at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:606) [jandex-1.0.3.Final-redhat-2.jar:1.0.3.Final-redhat-2]
    at org.jboss.jandex.Indexer.index(Indexer.java:640) [jandex-1.0.3.Final-redhat-2.jar:1.0.3.Final-redhat-2]
    at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:100) [jboss-as-server-7.4.0.Final-redhat-19.jar:7.4.0.Final-redhat-19]
    at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51) [jboss-as-server-7.4.0.Final-redhat-19.jar:7.4.0.Final-redhat-19]
    at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:159) [jboss-as-server-7.4.0.Final-redhat-19.jar:7.4.0.Final-redhat-19]
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1980) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1913) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_60-ea]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_60-ea]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_60-ea]

22:11:25,578 WARN  [org.jboss.as.server.deployment](MSC service thread 1-4) JBAS015852: Could not index class io/innerloop/neo4j/ogm/impl/metadata/PropertyMetadata.class at /C:/JBoss/jboss-eap-6.3/bin/content/CityMiners.war/WEB-INF/lib/java-neo4j-ogm-0.1.0.jar: java.lang.IllegalStateException: Unknown tag! pos=74 poolCount = 311
    at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:606) [jandex-1.0.3.Final-redhat-2.jar:1.0.3.Final-redhat-2]
    at org.jboss.jandex.Indexer.index(Indexer.java:640) [jandex-1.0.3.Final-redhat-2.jar:1.0.3.Final-redhat-2]
    at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:100) [jboss-as-server-7.4.0.Final-redhat-19.jar:7.4.0.Final-redhat-19]
    at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51) [jboss-as-server-7.4.0.Final-redhat-19.jar:7.4.0.Final-redhat-19]
    at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:159) [jboss-as-server-7.4.0.Final-redhat-19.jar:7.4.0.Final-redhat-19]
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1980) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1913) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_60-ea]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_60-ea]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_60-ea]

22:11:25,578 WARN  [org.jboss.as.server.deployment](MSC service thread 1-4) JBAS015852: Could not index class io/innerloop/neo4j/ogm/impl/metadata/RelationshipPropertiesClassMetadata.class at /C:/JBoss/jboss-eap-6.3/bin/content/CityMiners.war/WEB-INF/lib/java-neo4j-ogm-0.1.0.jar: java.lang.IllegalStateException: Unknown tag! pos=30 poolCount = 287
    at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:606) [jandex-1.0.3.Final-redhat-2.jar:1.0.3.Final-redhat-2]
    at org.jboss.jandex.Indexer.index(Indexer.java:640) [jandex-1.0.3.Final-redhat-2.jar:1.0.3.Final-redhat-2]
    at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:100) [jboss-as-server-7.4.0.Final-redhat-19.jar:7.4.0.Final-redhat-19]
    at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51) [jboss-as-server-7.4.0.Final-redhat-19.jar:7.4.0.Final-redhat-19]
    at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:159) [jboss-as-server-7.4.0.Final-redhat-19.jar:7.4.0.Final-redhat-19]
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1980) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1913) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_60-ea]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_60-ea]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_60-ea]

22:11:25,578 WARN  [org.jboss.as.server.deployment](MSC service thread 1-4) JBAS015852: Could not index class io/innerloop/neo4j/ogm/impl/metadata/ClassMetadata.class at /C:/JBoss/jboss-eap-6.3/bin/content/CityMiners.war/WEB-INF/lib/java-neo4j-ogm-0.1.0.jar: java.lang.IllegalStateException: Unknown tag! pos=84 poolCount = 463
    at org.jboss.jandex.Indexer.processConstantPool(Indexer.java:606) [jandex-1.0.3.Final-redhat-2.jar:1.0.3.Final-redhat-2]
    at org.jboss.jandex.Indexer.index(Indexer.java:640) [jandex-1.0.3.Final-redhat-2.jar:1.0.3.Final-redhat-2]
    at org.jboss.as.server.deployment.annotation.ResourceRootIndexer.indexResourceRoot(ResourceRootIndexer.java:100) [jboss-as-server-7.4.0.Final-redhat-19.jar:7.4.0.Final-redhat-19]
    at org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor.deploy(AnnotationIndexProcessor.java:51) [jboss-as-server-7.4.0.Final-redhat-19.jar:7.4.0.Final-redhat-19]
    at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:159) [jboss-as-server-7.4.0.Final-redhat-19.jar:7.4.0.Final-redhat-19]
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1980) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1913) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_60-ea]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_60-ea]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_60-ea]

22:11:27,562 WARN  [org.jboss.weld.deployer](MSC service thread 1-4) JBAS016003: Found beans.xml file in non-standard location: "/C:/JBoss/jboss-eap-6.3/bin/content/CityMiners.war/WEB-INF/classes/META-INF/beans.xml", war deployments should place beans.xml files into WEB-INF/beans.xml
22:11:27,609 INFO  [org.jboss.weld.deployer](MSC service thread 1-4) JBAS016002: Processing weld deployment CityMiners.war
22:11:27,625 INFO  [org.jboss.weld.deployer](MSC service thread 1-4) JBAS016005: Starting Services for CDI deployment: CityMiners.war
22:11:27,625 INFO  [org.jboss.weld.deployer](MSC service thread 1-1) JBAS016008: Starting weld service for deployment CityMiners.war
22:11:30,296 ERROR [org.jboss.msc.service.fail](MSC service thread 1-3) MSC000001: Failed to start service jboss.deployment.unit."CityMiners.war".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."CityMiners.war".WeldStartService: Failed to start service
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1936) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_60-ea]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_60-ea]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_60-ea]
Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408 Unsatisfied dependencies for type [Set<Service>] with qualifiers [@Default] at injection point [[parameter 1] of [constructor] @Inject com.google.common.util.concurrent.ServiceManager(Set<Service>)]
    at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:315)
    at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:284)
    at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:147)
    at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:167)
    at org.jboss.weld.bootstrap.Validator.validateBeans(Validator.java:386)
    at org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:371)
    at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:379)
    at org.jboss.as.weld.WeldStartService.start(WeldStartService.java:64)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1980) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1913) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
    ... 3 more

22:11:30,296 INFO  [org.jboss.as](Controller Boot Thread) JBAS015961: Http management interface listening on http://127.0.0.1:9994/management
22:11:30,296 INFO  [org.jboss.as](Controller Boot Thread) JBAS015951: Admin console listening on http://127.0.0.1:9994
22:11:30,296 ERROR [org.jboss.as](Controller Boot Thread) JBAS015875: JBoss EAP 6.3.0.GA (AS 7.4.0.Final-redhat-19) started (with errors) in 15187ms - Started 311 of 367 services (19 services failed or missing dependencies, 62 services are lazy, passive or on-demand)
22:11:30,296 ERROR [org.jboss.as.server](management-handler-thread - 2) JBAS015870: Deploy of deployment "CityMiners.war" was rolled back with the following failure message: 
{"JBAS014671: Failed services" => {"jboss.deployment.unit.\"CityMiners.war\".WeldStartService" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"CityMiners.war\".WeldStartService: Failed to start service
    Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408 Unsatisfied dependencies for type [Set<Service>] with qualifiers [@Default] at injection point [[parameter 1] of [constructor] @Inject com.google.common.util.concurrent.ServiceManager(Set<Service>)]"}}
22:11:30,312 INFO  [org.jboss.weld.deployer](MSC service thread 1-4) JBAS016009: Stopping weld service for deployment CityMiners.war
22:11:30,796 INFO  [org.jboss.as.server.deployment](MSC service thread 1-1) JBAS015877: Stopped deployment CityMiners.war (runtime-name: CityMiners.war) in 494ms
22:11:30,796 INFO  [org.jboss.as.controller](management-handler-thread - 2) JBAS014774: Service status report
JBAS014775:    New missing/unsatisfied dependencies:
      service jboss.deployment.unit."CityMiners.war".WeldBootstrapService (missing) dependents: [service jboss.web.deployment.default-host./CityMiners, service jboss.deployment.unit."CityMiners.war".component."javax.faces.webapp.FacetTag".WeldInstantiator, service jboss.deployment.unit."CityMiners.war".component."org.jboss.as.weld.webtier.jsp.JspInitializationListener".WeldInstantiator, service jboss.deployment.unit."CityMiners.war".component."org.apache.jasper.servlet.JspServlet".WeldInstantiator, JBAS014799: ... and 6 more ] 
      service jboss.deployment.unit."CityMiners.war".WeldStartService (missing) dependents: [service jboss.deployment.unit."CityMiners.war".component."javax.faces.webapp.FacetTag".WeldInstantiator, service jboss.deployment.unit."CityMiners.war".component."org.jboss.as.weld.webtier.jsp.JspInitializationListener".WeldInstantiator, service jboss.deployment.unit."CityMiners.war".component."org.apache.jasper.servlet.JspServlet".WeldInstantiator, service jboss.deployment.unit."CityMiners.war".component."com.sun.faces.config.ConfigureListener".WeldInstantiator, JBAS014799: ... and 5 more ] 
      service jboss.deployment.unit."CityMiners.war".component."com.sun.faces.config.ConfigureListener".CREATE (missing) dependents: [service jboss.deployment.unit."CityMiners.war".component."com.sun.faces.config.ConfigureListener".START] 
      service jboss.deployment.unit."CityMiners.war".component."com.sun.faces.config.ConfigureListener".START (missing) dependents: [service jboss.web.deployment.default-host./CityMiners, service jboss.deployment.unit."CityMiners.war".deploymentCompleteService] 
      service jboss.deployment.unit."CityMiners.war".component."com.sun.faces.config.ConfigureListener".WeldInstantiator (missing) dependents: [service jboss.deployment.unit."CityMiners.war".component."com.sun.faces.config.ConfigureListener".START] 
      service jboss.deployment.unit."CityMiners.war".component."javax.faces.webapp.FacetTag".CREATE (missing) dependents: [service jboss.deployment.unit."CityMiners.war".component."javax.faces.webapp.FacetTag".START] 
      service jboss.deployment.unit."CityMiners.war".component."javax.faces.webapp.FacetTag".START (missing) dependents: [service jboss.web.deployment.default-host./CityMiners, service jboss.deployment.unit."CityMiners.war".deploymentCompleteService] 
      service jboss.deployment.unit."CityMiners.war".component."javax.faces.webapp.FacetTag".WeldInstantiator (missing) dependents: [service jboss.deployment.unit."CityMiners.war".component."javax.faces.webapp.FacetTag".START] 
      service jboss.deployment.unit."CityMiners.war".component."javax.servlet.jsp.jstl.tlv.PermittedTaglibsTLV".CREATE (missing) dependents: [service jboss.deployment.unit."CityMiners.war".component."javax.servlet.jsp.jstl.tlv.PermittedTaglibsTLV".START] 
      service jboss.deployment.unit."CityMiners.war".component."javax.servlet.jsp.jstl.tlv.PermittedTaglibsTLV".START (missing) dependents: [service jboss.web.deployment.default-host./CityMiners, service jboss.deployment.unit."CityMiners.war".deploymentCompleteService] 
      service jboss.deployment.unit."CityMiners.war".component."javax.servlet.jsp.jstl.tlv.PermittedTaglibsTLV".WeldInstantiator (missing) dependents: [service jboss.deployment.unit."CityMiners.war".component."javax.servlet.jsp.jstl.tlv.PermittedTaglibsTLV".START] 
      service jboss.deployment.unit."CityMiners.war".component."javax.servlet.jsp.jstl.tlv.ScriptFreeTLV".CREATE (missing) dependents: [service jboss.deployment.unit."CityMiners.war".component."javax.servlet.jsp.jstl.tlv.ScriptFreeTLV".START] 
      service jboss.deployment.unit."CityMiners.war".component."javax.servlet.jsp.jstl.tlv.ScriptFreeTLV".START (missing) dependents: [service jboss.web.deployment.default-host./CityMiners, service jboss.deployment.unit."CityMiners.war".deploymentCompleteService] 
      service jboss.deployment.unit."CityMiners.war".component."javax.servlet.jsp.jstl.tlv.ScriptFreeTLV".WeldInstantiator (missing) dependents: [service jboss.deployment.unit."CityMiners.war".component."javax.servlet.jsp.jstl.tlv.ScriptFreeTLV".START] 
      service jboss.deployment.unit."CityMiners.war".component."org.apache.catalina.servlets.DefaultServlet".CREATE (missing) dependents: [service jboss.deployment.unit."CityMiners.war".component."org.apache.catalina.servlets.DefaultServlet".START] 
      service jboss.deployment.unit."CityMiners.war".component."org.apache.catalina.servlets.DefaultServlet".START (missing) dependents: [service jboss.web.deployment.default-host./CityMiners, service jboss.deployment.unit."CityMiners.war".deploymentCompleteService] 
      service jboss.deployment.unit."CityMiners.war".component."org.apache.catalina.servlets.DefaultServlet".WeldInstantiator (missing) dependents: [service jboss.deployment.unit."CityMiners.war".component."org.apache.catalina.servlets.DefaultServlet".START] 
      service jboss.deployment.unit."CityMiners.war".component."org.apache.jasper.servlet.JspServlet".CREATE (missing) dependents: [service jboss.deployment.unit."CityMiners.war".component."org.apache.jasper.servlet.JspServlet".START] 
      service jboss.deployment.unit."CityMiners.war".component."org.apache.jasper.servlet.JspServlet".START (missing) dependents: [service jboss.web.deployment.default-host./CityMiners, service jboss.deployment.unit."CityMiners.war".deploymentCompleteService] 
      service jboss.deployment.unit."CityMiners.war".component."org.apache.jasper.servlet.JspServlet".WeldInstantiator (missing) dependents: [service jboss.deployment.unit."CityMiners.war".component."org.apache.jasper.servlet.JspServlet".START] 
      service jboss.deployment.unit."CityMiners.war".component."org.jboss.as.weld.webtier.jsp.JspInitializationListener".CREATE (missing) dependents: [service jboss.deployment.unit."CityMiners.war".component."org.jboss.as.weld.webtier.jsp.JspInitializationListener".START] 
      service jboss.deployment.unit."CityMiners.war".component."org.jboss.as.weld.webtier.jsp.JspInitializationListener".START (missing) dependents: [service jboss.web.deployment.default-host./CityMiners, service jboss.deployment.unit."CityMiners.war".deploymentCompleteService] 
      service jboss.deployment.unit."CityMiners.war".component."org.jboss.as.weld.webtier.jsp.JspInitializationListener".WeldInstantiator (missing) dependents: [service jboss.deployment.unit."CityMiners.war".component."org.jboss.as.weld.webtier.jsp.JspInitializationListener".START] 
      service jboss.deployment.unit."CityMiners.war".component."org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher".CREATE (missing) dependents: [service jboss.deployment.unit."CityMiners.war".component."org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher".START] 
      service jboss.deployment.unit."CityMiners.war".component."org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher".START (missing) dependents: [service jboss.web.deployment.default-host./CityMiners, service jboss.deployment.unit."CityMiners.war".deploymentCompleteService] 
      service jboss.deployment.unit."CityMiners.war".component."org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher".WeldInstantiator (missing) dependents: [service jboss.deployment.unit."CityMiners.war".component."org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher".START] 
      service jboss.deployment.unit."CityMiners.war".jndiDependencyService (missing) dependents: [service jboss.web.deployment.default-host./CityMiners, service jboss.deployment.unit."CityMiners.war".component."com.sun.faces.config.ConfigureListener".START, service jboss.deployment.unit."CityMiners.war".component."org.apache.jasper.servlet.JspServlet".START, service jboss.deployment.unit."CityMiners.war".component."javax.faces.webapp.FacetTag".START, JBAS014799: ... and 6 more ] 
      service jboss.web.deployment.default-host./CityMiners (missing) dependents: [service jboss.deployment.unit."CityMiners.war".deploymentCompleteService] 
      service jboss.web.deployment.default-host./CityMiners.realm (missing) dependents: [service jboss.web.deployment.default-host./CityMiners, service jboss.deployment.unit."CityMiners.war".deploymentCompleteService] 
JBAS014777:   Services which failed to start:      service jboss.deployment.unit."CityMiners.war".WeldStartService

**Comment by mangrish** [comment]
Sorry for the delay. I was on holiday.

Did you make any more progress on this?
